### ISSUE TITLE
Deployment solution

### ISSUE THREAD

**Issue by enrico-ghidoni** [CntoDev/cnto-wp-website#20]
As discussed in private between myself and @JamesTheClarke as well as during R&D branch meeting on 11/02/2021, we need to come up with a decision on where to deploy the finished website.

Mentioned options include:
 - Existing `tools` server
 - External, WP-dedicated hosting solution
 - New VM to be added to our infrastructure

Factors to take into account:
 - Security risk
 - Maintainability, updates
 - Performances linked with network config and hardware resources

My personal concerns on deploying the new website on our machines, specifically the `tools` server, is that no member of the community as of now (and presumably in the future) is highly proficient in IT security, and since WordPress is known to be a generally unsafe product constant security checks are something to look at. As suggested by both @freghar and Seneram standard security policies enforced on the device, together with keeping the CMS updated, should provide us with enough protection from attacks.

My personal choice would be an external WP-dedicated hosting solution but it comes at the price of a monthly fee which, albeit small, would still be an additional drain over community funds. In terms of performance, this would probably be the best solution but we do not expect a high workload for the web server.

I would still prefer, going with a self-hosting solution, to deploy the new website on a different machine than the `tools` server since it already hosts critical services to the community (i.e. TeamSpeak). This way we can isolate the service and protect other ones already deployed. We would need to balance out the allocated resources to this new VM in order to still have room in the `tools` server and having a decently fast website, although given the available resources it shouldn't be a big issue. @JamesTheClarke how much storage space does the website take up?

All in all, considering costs and performance I admit the best solution would be to host the new website on our infrastructure on a semi-dedicated VM.

**Comment by JamesTheClarke** [comment]
As per the R&D Meeting from 11th of February 2021 we decided to host the website on our Tools server since Seneram ensured us that security-wise it would be the same as hosting it on an external provider (which would cost us monthly fees) and he was ok with us establishing the website there.

https://docs.google.com/document/d/1Qodi4lrKPBID_ZUC-OaZkMXElCzg82FlggAFLpW4_XM/edit

Issue #21 will detail the implementation steps. Closing this issue.
