### ISSUE TITLE
Configure basic WordPress instance on `tools` server

### ISSUE THREAD

**Issue by enrico-ghidoni** [CntoDev/cnto-wp-website#21]
Start the deployment of a barebone WordPress instance on the `tools` server to resume work on the project after backup failure.

**Comment by milivojm** [comment]
@enrico-ghidoni on docker? ;)

**Comment by enrico-ghidoni** [comment]
@milivojm that would make me a bit happier security-wise... I guess it's doable https://hub.docker.com/_/wordpress

**Comment by enrico-ghidoni** [comment]
Task list for completing the issue:

 - [x] Make sure the Docker image has good support for plugin installation
 - [x] Setup WordPress container
 - [x] Setup MariaDB instance (that's the only well-supported DBMS without additional headaches, unfortunately)
 - [x] Make local environment variable storage for WordPress connection strings to MySQL
 - [x] Setup infrastructure services to allow access to the website
   - [x] Configure reverse proxy for access
   - [x] Obtain and install SSL certificate for HTTPS only (hopefully Cloudflare will do, otherwise we'll opt for Let's Encrypt)
   - [x] Protect access with basic authentication while in development phase
   - [x] Link domain owned by @JamesTheClarke (cnto-arma.com)

@JamesTheClarke I'm not sure this will be done before CntoDev/ideas#12 and to avoid repetition of the loss you experienced last month I suggest waiting for it to be completed, so we can be sure nothing gets lost again and we (you) do not need to start over for a third time.

**Comment by JamesTheClarke** [comment]
Yeah, this matches with what I discussed with @milivojm . We agreed I won't be working on a second local version which may not be portable so I'll  wait till WP is setup to basic installation level whereas I can start working via the CMS/Dashboard.

Question: will the tools WP setup include a backup / rollback feature in case a test plugin somehow corrupts our DB? It's rare but it can still happen.

EDIT: maybe we should consider documenting the tools server WP setup on the wiki of this GitHub Repository: https://github.com/CntoDev/cnto-wp-website/wiki

**Comment by enrico-ghidoni** [comment]
The backup that is planned is a machine backup, so no rollback would be available for WordPress specifically. We can look into incremental backups of both the WordPress files and the MySQL DBMS. That is unless WordPress already has a tool to execute rollbacks.

The issue with deploying WordPress on Docker is that it's slightly harder to manage the filesystem according to our needs (manual plugin installation or specific backup policies for directories). What do you think @milivojm? Deploying with Docker is certainly quicker and more easily portable, but it comes at the cost of little configuration possible without spending some time configuring the image, at which point we'd lose the speed in setting it up.

For the documentation part, once deployment is complete I'll update a section on the project Wiki page.

**Comment by milivojm** [comment]
What extra image configuration steps are needed?

**Comment by enrico-ghidoni** [comment]
If the container hosting WordPress needs certain tools or software in addition to what is packed in the standard image, we need to define our own image. Which is no big issue really, it just adds a bit of complexity. My biggest concern is the need to install manual plugins into WordPress, for which we'd need to modify the `wordpress` directory that the container uses as reference volume. Again, it's totally possible I just want to make sure we don't block ourselves in a difficult situation if we need something in the future. I'm also okay with setting up the containers for testing and see how it goes.

**Comment by milivojm** [comment]
Let's be pragmatic here and deploy on barebone.

**Comment by enrico-ghidoni** [comment]
Since this involves more than R&D branch I'd like the topic to be discussed with @JamesTheClarke as well. Perhaps R&D March Monthly Meeting would be a good idea.

**Comment by Didr** [comment]
> If the container hosting WordPress needs certain tools or software in addition to what is packed in the standard image, we need to define our own image. Which is no big issue really, it just adds a bit of complexity. My biggest concern is the need to install manual plugins into WordPress, for which we'd need to modify the `wordpress` directory that the container uses as reference volume. Again, it's totally possible I just want to make sure we don't block ourselves in a difficult situation if we need something in the future. I'm also okay with setting up the containers for testing and see how it goes.

I see no issue with mounting a volume for persistence. Bitnami who runs one of the more popular Wordpress images recommends it: https://github.com/bitnami/bitnami-docker-wordpress#persisting-your-application
With the Wordpress directory mounted, I don't see more difficulty in using the Docker variant than deploying it on bare metal.

> Task list for completing the issue:

Looks good! I'm happy to help with all the tasks here.

**Comment by enrico-ghidoni** [comment]
You are absolutely right. That's my Docker boy! Just saved us a PHP installation. Also @Didr if you want to take the task on yourself feel free to do so :)

**Comment by enrico-ghidoni** [comment]
Requirements updated for using new domain and setting up authentication requirements. Waiting for @Didr to gain access to the server then the task can proceed.

**Comment by Didr** [comment]
This was setup and sent to Clarke on the 24th of March.

All that remains is adding cnto-arma.com to Cloudflare.

**Comment by enrico-ghidoni** [comment]
Do we have the certificate already?

**Comment by Didr** [comment]
> Do we have the certificate already?

I'm (lazily) relying on Cloudflare for the certificate. If we encounter any issues due to that I'll fix a letsencrypt cert too.

**Comment by enrico-ghidoni** [comment]
Good! I'll tick it off our list

**Comment by enrico-ghidoni** [comment]
@Didr can I close this? The one thing missing was linking WP to @JamesTheClarke's domain

**Comment by Didr** [comment]
> @Didr can I close this? The one thing missing was linking WP to @JamesTheClarke's domain

Go ahead.
